# Generated by Django 2.0.6 on 2018-06-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='exchange',
        ),
        migrations.AddField(
            model_name='exchange',
            name='coins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='exchange.Coin'),
        ),
    ]
