# Generated by Django 2.0.6 on 2018-06-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20180622_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='symbol',
            field=models.CharField(default='BTC', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
