# Generated by Django 2.0.6 on 2018-06-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_auto_20180622_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='coins',
        ),
        migrations.AddField(
            model_name='exchange',
            name='coins',
            field=models.ManyToManyField(blank=True, null=True, related_name='coins', to='exchange.Coin'),
        ),
    ]
