# Generated by Django 2.0.6 on 2018-06-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('exchange', '0005_auto_20180622_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='country',
        ),
        migrations.AddField(
            model_name='exchange',
            name='country',
            field=models.ManyToManyField(related_name='countries', to='country.Country'),
        ),
    ]
